<?php

namespace MCDH\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
	public function findFuturBookings($room){
		$queryBuilder = $this->createQueryBuilder('b');
		
		return $queryBuilder->getQuery()->getResult();
	}
	
}
