<?php

namespace MCDH\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use MCDH\UserBundle\Entity\User;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository{
	
	/**
	 * Sélectionner l'ensemble des hôtel, et les retourner avec une pagination
	 * 
	 * @param integer $page
	 * @param integer $nbPerPage
	 * @return Paginator
	 */
	public function getHotels($page, $nbPerPage)
	{
		//récupération de la requête sur l'hôtel
		$query = $this->createQueryBuilder('h')->getQuery();
	
		//définition de la requête
		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;
	
		//retourne les hotels avec la pagination
		return new Paginator($query, true);
	}
	
	/**
	 * Sélectionner l'ensemble des hôtels d'un propriétaire
	 *
	 * @param \MCDH\UserBundle\Entity\User
	 * @return multitype
	 */
	public function getHotelKeeperHotels($user)
	{
		//création de la requête
		$query = $this->createQueryBuilder('h')

			->where('h.hotelKeeper = :hotelkeeper')
				->setParameter('hotelkeeper', $user)
			
			->orderBy('h.name', 'ASC')
			->getQuery();
		
		//renvoie des résultats
		return $query->getResult();
	}
}
