mcdh_hotel_homepage:
    path:     /hotel/{page}
    defaults: { _controller: MCDHHotelBundle:Hotel:index , page: 1 }
    requirements:
        page: \d*
    
mcdh_hotel_add:
<<<<<<< HEAD
    path:     /hotel/add
=======
    path:     /addhotel
>>>>>>> origin/master
    defaults: { _controller: MCDHHotelBundle:Hotel:add }
    
mcdh_hotel_delete:
    path:     /hotel/delete/{idHotel}
    defaults: { _controller: MCDHHotelBundle:Hotel:delete }
    requirements:
        idHotel: \d+
    
mcdh_hotel_edit:
    path:     /hotel/edit/{idHotel}
    defaults: { _controller: MCDHHotelBundle:Hotel:edit }
    requirements:
        idHotel: \d+

mcdh_hotel_view:
    path:     /hotel/view/{idHotel}
    defaults: { _controller: MCDHHotelBundle:Hotel:view }
    requirements:
        idHotel: \d+
        
mcdh_hotel_edit_room:
    path:     /room/edit/{idRoom}
    defaults: { _controller: MCDHHotelBundle:Room:edit}
    requirements:
      idHotel: \d+
      idRoom: \d+
 
mcdh_hotel_add_room:
    path:     /hotel/{idHotel}/addroom
    defaults: { _controller: MCDHHotelBundle:Room:add}
    requirements:
      idRoom: \d+

mcdh_hotel_delete_room:
    path:     /room/delete/{idRoom}
    defaults: { _controller: MCDHHotelBundle:Room:delete}
    requirements:
      idRoom: \d+
    
mcdh_hotel_view_room:
    path:     /room/view/{idRoom}
    defaults: { _controller: MCDHHotelBundle:Room:view }
    requirements:
      idRoom: \d+
      
      
      
      

mcdh_hotel_view_booking:
    path:     /booking/view/{idBooking}
    defaults: { _controller: MCDHHotelBundle:Booking:view }
    requirements:
      idBooking: \d+

mcdh_hotel_edit_booking:
    path:     /booking/edit/{idBooking}
    defaults: { _controller: MCDHHotelBundle:Booking:edit }
    requirements:
      idBooking: \d+

mcdh_hotel_delete_booking:
    path:     /booking/delete/{idBooking}
    defaults: { _controller: MCDHHotelBundle:Booking:delete }
    requirements:
      idBooking: \d+

mcdh_hotel_add_booking:
    path:     /room/{idRoom}/addbooking
    defaults: { _controller: MCDHHotelBundle:Booking:add }
    requirements:
      idRoom: \d+
      
#mcdh_hotel_add_hotel_booking:
#    path:     /addbooking
#    defaults: { _controller: MCDHHotelBundle:Booking:addFromHotel }
#    requirements:
#      idHotel: \d*

#mcdh_room_add_room_booking:
#    path:     /addbooking
#    defaults: { _controller: MCDHHotelBundle:Booking:addFromRoom }
#    requirements:
#      idRoom: \d*
