mcdh_room_edit:
    path:     /edit/{id}
    defaults: { _controller: MCDHRoomBundle:Room:edit}
    requirements:
      id: \d+
 
mcdh_room_add:   
    path:     /add
    defaults: { _controller: MCDHRoomBundle:Room:add}

mcdh_room_delete:    
    path:     /delete/{id}
    defaults: { _controller: MCDHRoomBundle:Room:delete}
    requirements:
      id: \d+
    
mcdh_room_view:   
    path:     /view/{id}
    defaults: { _controller: MCDHRoomBundle:Room:view }
    requirements:
      id: \d+
    
    
